packages/template-blank-ng/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-enterprise-auth-ng/package.json
packages/template-health-survey-ng/package.json
packages/template-hello-world-ng/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-ng/package.json
packages/template-patient-care-ng/package.json
packages/template-tab-navigation-ng/package.json

Update webpack ng dev dependencies for nativescript-dev-webpack@0.20.2

chore: update webpack ng dev dependencies

---

packages/template-blank-vue/package.json

updating node-sass versions

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation/package.json
packages/template-enterprise-auth-ng/package.json
packages/template-enterprise-auth-ts/package.json
packages/template-enterprise-auth/package.json
packages/template-health-survey-ng/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-patient-care-ng/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation/package.json

Update tns-ios version to 5.3.1

chore: update to tns-ios@5.3.1

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation/package.json
packages/template-enterprise-auth-ng/package.json
packages/template-enterprise-auth-ts/package.json
packages/template-enterprise-auth/package.json
packages/template-health-survey-ng/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-patient-care-ng/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation/package.json

Revert bump of template version (it is auto bumped by lerna).

chore: revert bump of template version

---

packages/template-blank-ng/nsconfig.json
packages/template-blank-ts/nsconfig.json
packages/template-blank-vue/nsconfig.json
packages/template-blank/nsconfig.json
packages/template-drawer-navigation-ng/nsconfig.json
packages/template-drawer-navigation-ts/nsconfig.json
packages/template-drawer-navigation/nsconfig.json
packages/template-enterprise-auth-ng/nsconfig.json
packages/template-enterprise-auth-ts/nsconfig.json
packages/template-enterprise-auth/nsconfig.json
packages/template-health-survey-ng/nsconfig.json
packages/template-hello-world-ng/nsconfig.json
packages/template-hello-world-ts/nsconfig.json
packages/template-hello-world/nsconfig.json
packages/template-master-detail-kinvey-ng/nsconfig.json
packages/template-master-detail-kinvey-ts/nsconfig.json
packages/template-master-detail-kinvey/nsconfig.json
packages/template-master-detail-ng/nsconfig.json
packages/template-master-detail-ts/nsconfig.json
packages/template-master-detail-vue/nsconfig.json
packages/template-master-detail/nsconfig.json
packages/template-patient-care-ng/nsconfig.json
packages/template-tab-navigation-ng/nsconfig.json
packages/template-tab-navigation-ts/nsconfig.json
packages/template-tab-navigation/nsconfig.json

No HMR by default.
Enable HMR by default.

chore: enable hmr by default

---

packages/template-drawer-navigation-ng/src/app/app.component.html
packages/template-drawer-navigation-ts/app/app-root/app-root.xml
packages/template-drawer-navigation-vue/app/components/DrawerContent.vue
packages/template-drawer-navigation/app/app-root/app-root.xml

fix: Drawer content background with safe-area

---

packages/template-master-detail-kinvey-ts/app/cars/car-detail-edit-page/car-detail-edit-page.ts
packages/template-master-detail-kinvey/app/cars/car-detail-edit-page/car-detail-edit-page.js
packages/template-master-detail-ts/app/cars/car-detail-edit-page/car-detail-edit-page.ts
packages/template-master-detail/app/cars/car-detail-edit-page/car-detail-edit-page.js

Related to: https://github.com/NativeScript/NativeScript/pull/7382

chore: update showModal usage

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-enterprise-auth-ng/package.json
packages/template-enterprise-auth-ts/package.json
packages/template-enterprise-auth/package.json
packages/template-health-survey-ng/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-patient-care-ng/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation/package.json

Seems there was an issue with nativescript-phone@1.3.x and patient care template -- updated to latest 1.4.0.

chore: update nativescript-phone dependency

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-enterprise-auth-ng/package.json
packages/template-enterprise-auth-ts/package.json
packages/template-enterprise-auth/package.json
packages/template-health-survey-ng/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-patient-care-ng/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation/package.json

Update dependencies to latest RCs.

chore: update to 6.0 rc

---

packages/template-health-survey-ng/src/app/login/registration/registration-form.model.ts
packages/template-health-survey-ng/src/app/login/registration/registration.component.ts
packages/template-patient-care-ng/src/login/registration/registration-form.model.ts
packages/template-patient-care-ng/src/login/registration/registration.component.ts

Fixes breaking change in Kinvey UserService.signup(...) API introduced by https://github.com/Kinvey/js-sdk/pull/430 in kinvey-js-sdk@4.2.3 patch version as kinvey-js-sdk is a caret(^) dependency in kinvey-nativescript-sdk.

fix(kinvey): signup api breaking change

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-enterprise-auth-ng/package.json
packages/template-enterprise-auth-ts/package.json
packages/template-enterprise-auth/package.json
packages/template-health-survey-ng/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-patient-care-ng/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation/package.json

- (ng templates) update dependencies for angular 8.2.0
- (ng templates) remove @angular/http dependency
- (all templates) update runtime versions to latest (tns-android@6.0.1, tns-ios@6.0.2)

chore: update dependencies for angular 8.2.0

---

packages/template-master-detail-kinvey-ng/README.md
packages/template-master-detail-kinvey-ng/tools/kinvey/kinvey-database-setup.md
packages/template-master-detail-kinvey-ts/README.md
packages/template-master-detail-kinvey-ts/tools/kinvey/kinvey-database-setup.md
packages/template-master-detail-kinvey/README.md
packages/template-master-detail-kinvey/tools/kinvey/kinvey-database-setup.md
packages/template-master-detail-ng/README.md
packages/template-master-detail-ng/tools/firebase/firebase-database-setup.md
packages/template-master-detail-ts/README.md
packages/template-master-detail-ts/tools/firebase/firebase-database-setup.md
packages/template-master-detail-vue/tools/firebase/firebase-database-setup.md
packages/template-master-detail/README.md
packages/template-master-detail/tools/firebase/firebase-database-setup.md

Links got broken after we deleted the old and obsolete individual template repos.

chore(master-detail): fix broken links in readme

---

packages/template-blank-ng/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-blank-ts/app/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-blank-vue/app/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-blank/app/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-drawer-navigation-vue/app/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-health-survey-ng/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-hello-world-ng/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-hello-world-ts/app/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-hello-world/app/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-master-detail-kinvey-ts/app/cars/cars-list-page.ts
packages/template-master-detail-kinvey-ts/app/cars/cars-list-page.xml
packages/template-master-detail-kinvey-ts/app/cars/list-selector-modal-page/list-selector-modal-page.xml
packages/template-master-detail-kinvey/app/cars/cars-list-page.xml
packages/template-master-detail-kinvey/app/cars/list-selector-modal-page/list-selector-modal-page.xml
packages/template-master-detail-ts/app/cars/cars-list-page.ts
packages/template-master-detail-ts/app/cars/cars-list-page.xml
packages/template-master-detail-ts/app/cars/list-selector-modal-page/list-selector-modal-page.xml
packages/template-master-detail-vue/app/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-master-detail/app/cars/cars-list-page.xml
packages/template-master-detail/app/cars/list-selector-modal-page/list-selector-modal-page.xml
packages/template-patient-care-ng/App_Resources/Android/src/main/res/values-v21/styles.xml
packages/template-tab-navigation-vue/app/App_Resources/Android/src/main/res/values-v21/styles.xml

Add configuration for the status bar on Android.

fix(Android): unify status bar in templates

---

packages/template-hello-world-ng/src/app/item/items.component.html

Nest views of `ng-template` into a layout.

fix(template-hello-world-ng): add a layout to ng-template

---

.gitignore
packages/template-blank-ng/App_Resources/Android/src/main/res/values/styles.xml
packages/template-blank-ts/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-blank-vue/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-blank/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-drawer-navigation-ng/App_Resources/Android/src/main/res/values/styles.xml
packages/template-drawer-navigation-ts/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-drawer-navigation-vue/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-drawer-navigation/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-health-survey-ng/App_Resources/Android/src/main/res/values/styles.xml
packages/template-hello-world-ng/App_Resources/Android/src/main/res/values/styles.xml
packages/template-hello-world-ts/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-hello-world/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-master-detail-kinvey-ng/App_Resources/Android/src/main/res/values/styles.xml
packages/template-master-detail-kinvey-ts/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-master-detail-kinvey/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-master-detail-ng/App_Resources/Android/src/main/res/values/styles.xml
packages/template-master-detail-ts/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-master-detail-vue/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-master-detail/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-patient-care-ng/App_Resources/Android/src/main/res/values/styles.xml
packages/template-tab-navigation-ng/App_Resources/Android/src/main/res/values/styles.xml
packages/template-tab-navigation-ts/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-tab-navigation-vue/app/App_Resources/Android/src/main/res/values/styles.xml
packages/template-tab-navigation/app/App_Resources/Android/src/main/res/values/styles.xml

Relates to https://github.com/NativeScript/NativeScript/issues/7800.

feat(Android): opt-in to force dark

---

packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ng/src/app/cars/_car-list.component.scss
packages/template-master-detail-kinvey-ng/src/app/cars/car-detail-edit/_car-detail-edit.component.scss
packages/template-master-detail-kinvey-ng/src/app/cars/car-detail-edit/my-image-add-remove/_my-image-add-remove.component.scss
packages/template-master-detail-ng/package.json
packages/template-master-detail-ng/src/app/cars/_car-list.component.scss
packages/template-master-detail-ng/src/app/cars/car-detail-edit/_car-detail-edit.component.scss
packages/template-master-detail-ng/src/app/cars/car-detail-edit/my-image-add-remove/_my-image-add-remove.component.scss
packages/template-tab-navigation-ng/src/app/home/home.component.html
packages/template-tab-navigation-ng/src/app/shared/data.service.ts

https://angular.io/guide/component-styles

fix(templates-ng): host context scope selectors

---

packages/template-master-detail-vue/package.json

So changing system appearance at runtime works properly for the application.

feat(master-detail-vue): update RadListView

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

- tns-template-blank-ng@6.2.4
- tns-template-blank-ts@6.2.4
- tns-template-blank-vue@6.2.4
- tns-template-blank@6.2.4
- tns-template-drawer-navigation-ng@6.2.4
- tns-template-drawer-navigation-ts@6.2.4
- tns-template-drawer-navigation-vue@6.2.4
- tns-template-drawer-navigation@6.2.4
- tns-template-hello-world-ng@6.2.4
- tns-template-hello-world-ts@6.2.4
- tns-template-hello-world@6.2.4
- tns-template-master-detail-kinvey-ng@6.2.4
- tns-template-master-detail-kinvey-ts@6.2.4
- tns-template-master-detail-kinvey@6.2.4
- tns-template-master-detail-ng@6.2.4
- tns-template-master-detail-ts@6.2.4
- tns-template-master-detail-vue@6.2.4
- tns-template-master-detail@6.2.4
- tns-template-tab-navigation-ng@6.2.4
- tns-template-tab-navigation-ts@6.2.4
- tns-template-tab-navigation-vue@6.2.4
- …

merge release into master

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

- tns-template-blank-ng@6.3.0
- tns-template-blank-ts@6.3.0
- tns-template-blank-vue@6.3.0
- tns-template-blank@6.3.0
- tns-template-drawer-navigation-ng@6.3.0
- tns-template-drawer-navigation-ts@6.3.0
- tns-template-drawer-navigation-vue@6.3.0
- tns-template-drawer-navigation@6.3.0
- tns-template-hello-world-ng@6.3.0
- tns-template-hello-world-ts@6.3.0
- tns-template-hello-world@6.3.0
- tns-template-master-detail-kinvey-ng@6.3.0
- tns-template-master-detail-kinvey-ts@6.3.0
- tns-template-master-detail-kinvey@6.3.0
- tns-template-master-detail-ng@6.3.0
- tns-template-master-detail-ts@6.3.0
- tns-template-master-detail-vue@6.3.0
- tns-template-master-detail@6.3.0
- tns-template-tab-navigation-ng@6.3.0
- tns-template-tab-navigation-ts@6.3.0
- tns-template-tab-navigation-vue@6.3.0
- …

chore: update dependencies for 6.3

---

packages/template-hello-world-ng/README.md

chore: fix npm link

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

- tns-template-blank-ng@6.3.1
- tns-template-blank-ts@6.3.1
- tns-template-blank-vue@6.3.1
- tns-template-blank@6.3.1
- tns-template-drawer-navigation-ng@6.3.1
- tns-template-drawer-navigation-ts@6.3.1
- tns-template-drawer-navigation-vue@6.3.1
- tns-template-drawer-navigation@6.3.1
- tns-template-hello-world-ng@6.3.1
- tns-template-hello-world-ts@6.3.1
- tns-template-hello-world@6.3.1
- tns-template-master-detail-kinvey-ng@6.3.1
- tns-template-master-detail-kinvey-ts@6.3.1
- tns-template-master-detail-kinvey@6.3.1
- tns-template-master-detail-ng@6.3.1
- tns-template-master-detail-ts@6.3.1
- tns-template-master-detail-vue@6.3.1
- tns-template-master-detail@6.3.1
- tns-template-tab-navigation-ng@6.3.1
- tns-template-tab-navigation-ts@6.3.1
- tns-template-tab-navigation-vue@6.3.1
- …

chore: update android runtime.6.3.1

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

Updated android runtime to the latest 6.4.1 version

chore: update android runtime to 6.4.1

---

packages/template-blank-ng/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

chore: merge release in master

---

packages/template-blank-react/package.json

Note: I've already published the new React template to npm based on this branch.

fix(react): Fix ListView by updating to RNS v1.0.6

---

packages/template-blank-react/package.json

Fixes the issue mentioned in https://github.com/NativeScript/nativescript-cli/issues/5425#issuecomment-719176102

fix: Swap @react-navigation/native for @react-navigation/core

---

README.md
packages/template-blank-vue-ts/package.json
packages/template-blank-vue/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

Replace `node-sass` package with `sass` package.
Fixed slack invitation link in README.md

chore: replace node sass

---

packages/template-blank-react/package.json

Runtime error upon trying to perform stack navigation.
Should survive stack navigation. Follow-up PR will make lateral navigation work.

fix(react): Update template to use RNS with beta support for NS8

---

.github/workflows/test.yml
packages/template-blank-ng/package.json
packages/template-blank-react/package.json
packages/template-blank-svelte/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json
shared/App_Resources/Android/app.gradle
shared/App_Resources/Android/before-plugins.gradle
shared/App_Resources/Android/src/main/AndroidManifest.xml
shared/App_Resources/Android/src/main/res/values-v21/colors.xml
shared/App_Resources/Android/src/main/res/values-v21/styles.xml
shared/App_Resources/Android/src/main/res/values-v29/styles.xml
shared/App_Resources/Android/src/main/res/values/colors.xml

feat: 8.2.0

---

packages/template-blank-react/package.json
packages/template-blank-react/src/components/MainStack.tsx

React template was failing at runtime.

fix: navigation in react template

---

packages/template-blank-ng/package.json
packages/template-blank-react/package.json
packages/template-blank-svelte/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue-ts/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

feat: 8.4.0

---

packages/template-blank-react/package.json

Updates deps to RNS v5, which fixes startup and migrates to React 18.

fix(react): fix startup (and migrate to React 18)

---

packages/template-blank-svelte-vision/package.json
packages/template-blank-svelte-vision/types/references.d.ts
packages/template-blank-svelte/package.json
packages/template-blank-svelte/types/references.d.ts

Some svelte dependencies are outdated and not in sync with dependency of TypeScript.
Svelte dependencies are up to date.

Svelte template update

---

packages/template-blank-ng/package.json
packages/template-blank-react-vision/package.json
packages/template-blank-react/package.json
packages/template-blank-solid-vision/package.json
packages/template-blank-solid/package.json
packages/template-blank-svelte-vision/package.json
packages/template-blank-svelte/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue-ts/package.json
packages/template-blank-vue-vision/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng-vision/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts-vision/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

- Resolves several deprecation warnings with latest sass

fix: theme sass deprecation
