NativeScript/nativescript-app-templates

packages/template-blank-ng/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-blank-ts/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-blank-vue/app/App_Resources/Android/AndroidManifest.xml
packages/template-blank/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-drawer-navigation-ng/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-drawer-navigation-ts/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-drawer-navigation/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-health-survey-ng/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-hello-world-ng/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-hello-world-ts/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-hello-world/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-master-detail-kinvey-ng/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-master-detail-kinvey-ts/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-master-detail-kinvey/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-master-detail-ng/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-master-detail-ts/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-master-detail-vue/app/App_Resources/Android/AndroidManifest.xml
packages/template-master-detail/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-patient-care-ng/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-tab-navigation-ng/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-tab-navigation-ts/app/App_Resources/Android/src/main/AndroidManifest.xml
packages/template-tab-navigation/app/App_Resources/Android/src/main/AndroidManifest.xml

Extend activity [configuration changes list]  (https://developer.android.com/guide/topics/manifest/activity-element).
_Lists configuration changes that the activity will handle itself. When a configuration change occurs at runtime, the activity is shut down and restarted by default, but declaring a configuration with this attribute will prevent the activity from being restarted. Instead, the activity remains running and its onConfigurationChanged() method is called._
Originating from https://github.com/NativeScript/NativeScript/issues/6753

fix(android-manifest): crash when access ing topmost frame in multi-window mode

---

packages/template-master-detail-kinvey-ts/hooks/after-createProject/after-createProject.js
packages/template-master-detail-kinvey/hooks/after-createProject/after-createProject.js

Fixes after-createProject hook error in master-detail-kinvey & master-detail-kinvey-ts:
```
15:56:26 Execute command: C:\Git\nativescript-tooling-qa\node_modules\.bin\tns create master-detail-kinvey --template C:\Git\nativescript-tooling-qa\sut\template-master-detail-kinvey.tgz 
15:57:08 OUTPUT: 
{ [Error: ENOENT: no such file or directory, open 'C:\Git\nativescript-tooling-qa\master-detail-kinvey\App_Resources\Android\google-services.json']
errno: -4058,
code: 'ENOENT',
syscall: 'open',
path:
'C:\\Git\\nativescript-tooling-qa\\master-detail-kinvey\\App_Resources\\Android\\google-services.json' }
Project master-detail-kinvey was successfully created.
```

fix: after-createProject hook

---

packages/template-hello-world-ng/src/app/item/items.component.html

Fix no-dimension listview in stacklayout warning:
```
JS: Avoid using ListView or ScrollView with no explicit height set inside StackLayout. Doing so might results in poor user interface performance and a poor user experience.
```

fix: no-dimension listview in stacklayout warning

---

packages/template-blank-vue/package.json
packages/template-master-detail-vue/package.json

Bump to nativescript-vue@2.2
Templates use nativescript-vue@2.0
Bump to nativescript-vue@2.2

chore: bump nativescript-vue version

---

packages/template-drawer-navigation-ng/tslint.json
packages/template-drawer-navigation-ts/tslint.json
packages/template-enterprise-auth-ng/tslint.json
packages/template-enterprise-auth-ts/tslint.json
packages/template-health-survey-ng/tslint.json
packages/template-master-detail-kinvey-ng/tslint.json
packages/template-master-detail-kinvey-ts/tslint.json
packages/template-master-detail-ng/tslint.json
packages/template-master-detail-ts/tslint.json
packages/template-patient-care-ng/tslint.json
packages/template-tab-navigation-ng/tslint.json
packages/template-tab-navigation-ts/tslint.json

Warn when deprecated APIs are used for TypeScript/Angular flavors.

chore: add deprecation tslint rule

---

package.json
packages/template-patient-care-ng/.npmignore

Explicitly whitelist "core" folder name due to https://github.com/lerna/lerna/issues/1932 to fix tns-template-health-survey-ng template:
``` bash
tns run ios
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Found peer TypeScript 3.1.6
src/app/consent/consent-review/consent/consent.component.ts(8,35): error TS2307: Cannot find module '../../../core/task-manager/steps'.
src/app/consent/consent-review/consent/consent.component.ts(9,36): error TS2307: Cannot find module '../../../core/task-manager/task-manager.service'.
src/app/consent/consent-sharing/consent-sharing.component.ts(4,36): error TS2307: Cannot find module '../../core/task-manager/steps'.
src/app/consent/consent-sharing/consent-sharing.component.ts(5,36): error …
```

fix: explicitly whitelist core folder name

---

packages/template-blank-vue/app/App_Resources/iOS/LaunchScreen.storyboard
packages/template-master-detail-vue/app/App_Resources/iOS/LaunchScreen.storyboard

Launch images were clipped on the bottom on iOS X devices for vue templates.

chore(ios-vue): update launch images for x devices

---

packages/template-blank-ng/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-enterprise-auth-ng/package.json
packages/template-health-survey-ng/package.json
packages/template-hello-world-ng/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-ng/package.json
packages/template-patient-care-ng/package.json
packages/template-tab-navigation-ng/package.json

Extra packages that most users don't use and currently we don't have resources to maintain it (not working with ng8).

chore: remove schematics dev dependency

---

packages/template-blank-ng/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-enterprise-auth-ng/package.json
packages/template-health-survey-ng/package.json
packages/template-hello-world-ng/package.json
packages/template-master-detail-kinvey-ng/package.json
packages/template-master-detail-ng/package.json
packages/template-patient-care-ng/package.json
packages/template-tab-navigation-ng/package.json

Getting the following warning:
```
npm WARN @angular/core@8.0.0 requires a peer of zone.js@~0.9.1 but none is installed. You must install peer dependencies yourself.
```
So updated zone.js to latest.

chore: update zone.js to latest

---

packages/template-blank-ng/tsconfig.json
packages/template-blank-ts/tsconfig.json
packages/template-drawer-navigation-ng/tsconfig.json
packages/template-drawer-navigation-ts/tsconfig.json
packages/template-enterprise-auth-ng/tsconfig.json
packages/template-enterprise-auth-ts/tsconfig.json
packages/template-health-survey-ng/tsconfig.json
packages/template-hello-world-ng/tsconfig.json
packages/template-hello-world-ts/tsconfig.json
packages/template-master-detail-kinvey-ng/tsconfig.json
packages/template-master-detail-kinvey-ts/tsconfig.json
packages/template-master-detail-ng/tsconfig.json
packages/template-master-detail-ts/tsconfig.json
packages/template-patient-care-ng/tsconfig.json
packages/template-tab-navigation-ng/tsconfig.json
packages/template-tab-navigation-ts/tsconfig.json

Using `skipLibCheck` to skip type checking of all declaration files (*.d.ts) in `node_modules`. Applied to all  TypeScript and Angular templates.
Closes: https://github.com/NativeScript/NativeScript/issues/7552

feat: add skipLibCheck: true for all TypeScript enabled templates

---

packages/template-hello-world-ng/src/app/item/items.component.ts

This comment is not true. The service is declared with the `providedIn` construct in the service file.

fix: incorrect comment about injection

---

packages/template-master-detail-kinvey-ts/package.json
packages/template-master-detail-kinvey/package.json

Force JS & TS Kinvey templates to use tslib@^1.9.3 (i.e. the version referenced by tns-core-modules 1.10.0) -- currently it seems there is a breaking change between tslib@1.9.3 and tslib@1.10.0 which causes the tns-core-modules code (transpiled agains 1.10.0) to use a new spread operator syntax that does not work with 1.9.3. On the other hand kinvey-nativescript-sdk@4.2.3 uses tslib@1.9.3 as a hardcoded version and this somehow forces the whole app to use 1.9.3.

chore(kinvey): force tslib@^1.9.3

---

packages/template-blank-ng/tsconfig.tns.json
packages/template-blank-ts/tsconfig.tns.json
packages/template-drawer-navigation-ng/tsconfig.tns.json
packages/template-drawer-navigation-ts/tsconfig.tns.json
packages/template-health-survey-ng/tsconfig.tns.json
packages/template-hello-world-ng/tsconfig.tns.json
packages/template-hello-world-ts/tsconfig.tns.json
packages/template-master-detail-kinvey-ng/tsconfig.tns.json
packages/template-master-detail-kinvey-ts/tsconfig.tns.json
packages/template-master-detail-ng/tsconfig.tns.json
packages/template-master-detail-ts/tsconfig.tns.json
packages/template-patient-care-ng/tsconfig.tns.json
packages/template-tab-navigation-ng/tsconfig.tns.json
packages/template-tab-navigation-ts/tsconfig.tns.json

Address the following warning from nativescript-dev-webpack on `npm install`:
```
> nativescript-dev-webpack@1.2.0 postinstall /Users/x/github/drawer-ts/node_modules/nativescript-dev-webpack
> node postinstall.js
The current project contains a tsconfig.tns.json file located at /Users/x/github/drawer-ts/tsconfig.tns.json that differs from the one in the new version of the nativescript-dev-webpack plugin located at /Users/x/github/drawer-ts/node_modules/nativescript-dev-webpack/templates/tsconfig.tns.json. Some of the plugin features may not work as expected until you manually update the tsconfig.tns.json file or automatically update it using "./node_modules/.bin/update-ns-webpack --configs" command.
```

fix(webpack): tsconfig.tns.json warning

---

packages/template-blank-ng/src/app/app-routing.module.ts
packages/template-drawer-navigation-ng/src/app/app-routing.module.ts
packages/template-health-survey-ng/src/app/app-routing.module.ts
packages/template-master-detail-kinvey-ng/src/app/app-routing.module.ts
packages/template-master-detail-ng/src/app/app-routing.module.ts
packages/template-patient-care-ng/src/app-routing.module.ts
packages/template-tab-navigation-ng/src/app/app-routing.module.ts

Fixes `Runtime is not loaded` error in Angular Android templates with --env.aot option specified:
```
Restarting application on device emulator-5562...
Successfully synced application org.nativescript.TestApp on device emulator-5562.
ActivityManager: Start proc 3732:org.nativescript.TestApp/u0a55 for activity org.nativescript.TestApp/com.tns.NativeScriptActivity
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: firebase.init done
JS: ERROR Error: Uncaught (in promise): Error: Runtime compiler is not loaded
JS: Error: Runtime compiler is not loaded
JS:     at Compiler._throwError (file:///node_modules/@angular/core/fesm5/core.js:25788:0) [angular]
JS:     at …
```

fix(ng-android): runtime compiler not loaded error with aot

---

packages/template-blank-vue/jsconfig.json
packages/template-blank/jsconfig.json
packages/template-drawer-navigation-vue/jsconfig.json
packages/template-drawer-navigation/jsconfig.json
packages/template-hello-world/jsconfig.json
packages/template-master-detail-kinvey/jsconfig.json
packages/template-master-detail-vue/jsconfig.json
packages/template-master-detail/jsconfig.json
packages/template-tab-navigation/jsconfig.json

This PR removes the alias for using *short imports* from
`tns-core-modules` from the `jsconfig.json` files.

chore(js): remove short import alias

---

packages/template-health-survey-ng/App_Resources/iOS/Info.plist
packages/template-patient-care-ng/App_Resources/iOS/Info.plist

Temporarily hardcode light mode for health survey & patient care templates as we will not be able to migrate them to theme v2 for {N} 6.2.0 release.

fix: hardcode light mode temporarily

---

packages/template-blank-ng/.vscode/extensions.json
packages/template-blank-ts/.vscode/extensions.json
packages/template-blank-vue/.vscode/extensions.json
packages/template-blank/.vscode/extensions.json
packages/template-drawer-navigation-ng/.vscode/extensions.json
packages/template-drawer-navigation-ts/.vscode/extensions.json
packages/template-drawer-navigation-vue/.vscode/extensions.json
packages/template-drawer-navigation/.vscode/extensions.json
packages/template-health-survey-ng/.vscode/extensions.json
packages/template-hello-world-ng/.vscode/extensions.json
packages/template-hello-world-ts/.vscode/extensions.json
packages/template-hello-world/.vscode/extensions.json
packages/template-master-detail-kinvey-ng/.vscode/extensions.json
packages/template-master-detail-kinvey-ts/.vscode/extensions.json
packages/template-master-detail-kinvey/.vscode/extensions.json
packages/template-master-detail-ng/.vscode/extensions.json
packages/template-master-detail-ts/.vscode/extensions.json
packages/template-master-detail-vue/.vscode/extensions.json
packages/template-master-detail/.vscode/extensions.json
packages/template-tab-navigation-ng/.vscode/extensions.json
packages/template-tab-navigation-ts/.vscode/extensions.json
packages/template-tab-navigation-vue/.vscode/extensions.json
packages/template-tab-navigation/.vscode/extensions.json

Relates to https://github.com/NativeScript/nativescript-vscode-extension/issues/272
When a new {N} application is created - nothing more happens.
When a new {N} application is created from one of the templates - the NativeScript VSCode extension is suggested if it's not installed already.
Implements https://github.com/NativeScript/nativescript-vscode-extension/issues/272

feat: suggest NativeScript VSCode extension

---

packages/template-blank-ng/tools/vscode.extensions.json
packages/template-blank-react/hooks/after-createProject/after-createProject.js
packages/template-blank-svelte/tools/vscode.extensions.json
packages/template-blank-ts/tools/vscode.extensions.json
packages/template-blank-vue/tools/vscode.extensions.json
packages/template-blank/tools/vscode.extensions.json
packages/template-drawer-navigation-ng/tools/vscode.extensions.json
packages/template-drawer-navigation-ts/tools/vscode.extensions.json
packages/template-drawer-navigation-vue/tools/vscode.extensions.json
packages/template-drawer-navigation/tools/vscode.extensions.json
packages/template-hello-world-ng/tools/vscode.extensions.json
packages/template-hello-world-ts/tools/vscode.extensions.json
packages/template-hello-world/tools/vscode.extensions.json
packages/template-master-detail-ng/tools/vscode.extensions.json
packages/template-master-detail-ts/tools/vscode.extensions.json
packages/template-master-detail-vue/tools/vscode.extensions.json
packages/template-master-detail/tools/vscode.extensions.json
packages/template-tab-navigation-ng/tools/vscode.extensions.json
packages/template-tab-navigation-ts/tools/vscode.extensions.json
packages/template-tab-navigation-vue/tools/vscode.extensions.json
packages/template-tab-navigation/tools/vscode.extensions.json

just a tiny small fix :)
Any new project (except template-blank-react) created with an template get's a vscode extension recommendation, which is currently refering to "telerik.nativescript", which is now listed under "nativescript.nativescript". That results in a small warning box:
The recommended extension is now "nativescript.nativescript"

fix: broken vscode extension recommendation

---

packages/template-blank-react/package.json
packages/template-blank-react/src/components/FirstScreen.tsx
packages/template-blank-react/src/components/SecondScreen.tsx

RNS Navigation v2 renames an import, which I neglected to take care of in the last PR.

fix: Renamed RNS Navigation exports

---

packages/template-drawer-navigation-ts/package.json

The Build fails because the entry point does not exists
Build ends successfully
Fixes/Implements/Closes #[Issue Number].
- Fix Package.json main entry point

fix: package.json wrong entrypoint in template

---

packages/template-blank-vue-ts/.gitignore
packages/template-blank-vue-ts/hooks/after-createProject/after-createProject.js
packages/template-blank-vue-ts/package.json

Added `after-createProject.js` to hooks

fix: missing template-blank-vue-ts afterCreate hooks

---

packages/template-blank-vue-ts/tsconfig.json

**BROKEN LINK**
**ISSUE TAB IS NOT SET UP IN THIS REPO**
**There are no tests in this repo**
tsconfig.json compilerOptions has strict not set which differs from the recommended configuration in the Vue.js documentation ([see here](https://v3.vuejs.org/guide/typescript-support.html#recommended-configuration)).
As it says in the VueJS docs:
> Note that you have to include strict: true (or at least noImplicitThis: true which is a part of strict flag) to leverage type checking of this in component methods otherwise it is always treated as any type.
With the current set up, all references of `this` within component methods are treated as an `any` type which is not useful for type checking.
By adding this one line to the Tsconfig.json, type checking will work properly in Vue component methods …

[Vue Blank TS] Add strict : true to tsconfig compilerOptions

---

packages/template-drawer-navigation-ng/src/polyfills.ts
packages/template-drawer-navigation-ng/tsconfig.json
packages/template-tab-navigation-ng/src/polyfills.ts
packages/template-tab-navigation-ng/tsconfig.json

polyfills missing from these ng templates.
ns create should result in a runnable project using these templates
Fixes/Implements/Closes #[Issue Number].

Fix ng templates missing polyfils

---

packages/template-blank-react/package.json

`react-refresh` has duplicate dependencies across the projects and `@nativescript/webpack@5`
`react-refresh` is now an internal dependencies of `@nativescript/webpack@5` and is not a dependencies of the projects themselves.

chore(template-blank-react): more react-refresh to webpack5

---

package.json
packages/template-blank-ng/package.json
packages/template-blank-react-vision/package.json
packages/template-blank-react/package.json
packages/template-blank-solid-vision/package.json
packages/template-blank-solid/package.json
packages/template-blank-svelte-vision/package.json
packages/template-blank-svelte/package.json
packages/template-blank-ts/package.json
packages/template-blank-vue-ts/package.json
packages/template-blank-vue-vision/package.json
packages/template-blank-vue/package.json
packages/template-blank/package.json
packages/template-drawer-navigation-ng/package.json
packages/template-drawer-navigation-ts/package.json
packages/template-drawer-navigation-vue/package.json
packages/template-drawer-navigation/package.json
packages/template-hello-world-ng-vision/package.json
packages/template-hello-world-ng/package.json
packages/template-hello-world-ts-vision/package.json
packages/template-hello-world-ts/package.json
packages/template-hello-world/package.json
packages/template-master-detail-ng/package.json
packages/template-master-detail-ts/package.json
packages/template-master-detail-vue/package.json
packages/template-master-detail/package.json
packages/template-tab-navigation-ng/package.json
packages/template-tab-navigation-ts/package.json
packages/template-tab-navigation-vue/package.json
packages/template-tab-navigation/package.json

feat: 8.8 updates

---

packages/template-blank-svelte-vision/package.json
packages/template-blank-svelte-vision/svelte.config.js
packages/template-blank-svelte/app/app.css
packages/template-blank-svelte/package.json
packages/template-blank-svelte/svelte.config.js

Updated the svelte templates to use community plugins.
Also improved the svelte config:
* remove warnings in svelte check if using __ANDROID__ or __IOS__ in templates.
* disabled the native-preprocessor as it is dead slow and added a comment to explain

Svelte update
